Repository HorangITBeanS/COMFIE-iOS, pull requests merged in 2025-07, with the labels that each got.

#35 ✨ Feat: #34 컴피존 설정 기능 구현
  COMFIE.xcodeproj/project.pbxproj
  COMFIE/App/DIContainer/DIContainer.swift
  COMFIE/Data/CoreData/Extensions/ComfieZone+fromEntity.swift
  COMFIE/Data/Repository/ComfieZoneRepository/ComfieZoneRepository.swift
  COMFIE/Data/Repository/ComfieZoneRepository/ComfieZoneRepositoryProtocol.swift
  COMFIE/Domain/UseCase/LocationUseCase.swift
  COMFIE/Presentation/ComfieZoneSetting/BottomSheet/ComfieZoneSettingBottomSheet.swift
  COMFIE/Presentation/ComfieZoneSetting/ComfieZoneConstant.swift
  COMFIE/Presentation/ComfieZoneSetting/ComfieZoneSettingStore.swift
  COMFIE/Presentation/ComfieZoneSetting/ComfieZoneSettingView.swift
  COMFIE/Presentation/Memo/MemoCell.swift
  COMFIE/Presentation/Memo/MemoListView.swift
  COMFIE/Presentation/Memo/MemoStore.swift
  COMFIE/Presentation/Memo/MemoView.swift
  COMFIE/Presentation/Onboarding/OnboardingView.swift
  COMFIE/Resources/Localization/Localizable.xcstrings
  COMFIE/Resources/Localization/StringLiterals/StringLiterals+ComfieZoneSetting.swift
  COMFIE/Service/LocationService.swift
Labels: 이오 🐧, Feature 🍄, 리뷰해주세요 ☃️

#43 ✨ Feat: #42 컴피존 내 메모 입력 시 이모지 자동 변환 비활성화
  COMFIE/Presentation/Memo/MemoInput/MemoInputUITextView.swift
Labels: 호랑 🐯, Feature 🍄, 리뷰해주세요 ☃️

#46 Fix: 2차 QA UI 관련 사항 반영
  COMFIE/Resources/Assets.xcassets/Image/tutorial.imageset/Contents.json
  COMFIE/Resources/Assets.xcassets/Image/tutorial.imageset/tuto 1.png
  COMFIE/Resources/Assets.xcassets/Image/tutorial.imageset/tuto.png
  COMFIE/Resources/Assets.xcassets/Image/tutorial.imageset/tuto@2x 1.png
  COMFIE/Resources/Assets.xcassets/Image/tutorial.imageset/tuto@2x.png
  COMFIE/Resources/Assets.xcassets/Image/tutorial.imageset/tuto@3x 1.png
  COMFIE/Resources/Assets.xcassets/Image/tutorial.imageset/tuto@3x.png
  COMFIE/Resources/Localization/Localizable.xcstrings
Labels: 구리스 🐶, Chore ⚙️, 리뷰해주세요 ☃️

#45 ✨ Feat: 사용자 실시간 위치에 따른 지도 및 컴피존 내외 여부 변경
  COMFIE/Domain/UseCase/LocationUseCase.swift
  COMFIE/Presentation/ComfieZoneSetting/ComfieZoneSettingStore.swift
  COMFIE/Presentation/ComfieZoneSetting/ComfieZoneSettingView.swift
  COMFIE/Presentation/Memo/MemoStore.swift
  COMFIE/Service/LocationService.swift
Labels: 이오 🐧, Feature 🍄, 리뷰해주세요 ☃️

#47 🐛 Fix: CPU 점유율 203-205% -> 1-2% 감소
  COMFIE/App/COMFIEApp.swift
  COMFIE/App/COMFIERoutingView.swift
  COMFIE/App/DIContainer/DIContainer.swift
  COMFIE/App/Router/Route.swift
  COMFIE/App/Router/Router.swift
Labels: 이오 🐧, Fix 🚑

#49 Fix: 회고 관련 QA 사항 이슈 수정
  COMFIE/Data/CoreData/CoreDataService.swift
  COMFIE/Data/CoreData/CoreDataTestView.swift
  COMFIE/Data/CoreData/Extensions/Memo+fromEntity.swift
  COMFIE/Data/CoreData/Extensions/Memo+toEntity.swift
  COMFIE/Data/CoreData/Extensions/Memo+with.swift
  COMFIE/Data/CoreData/UserRecordModel.xcdatamodeld/UserRecordModel.xcdatamodel/contents
  COMFIE/Domain/Entity/Memo.swift
  COMFIE/Presentation/Memo/MemoCell.swift
  COMFIE/Presentation/Retrospection/RetrospectionStore.swift
Labels: 구리스 🐶, 리뷰해주세요 ☃️, Fix 🚑
